### ISSUE TITLE
Note: `generate.ts` will need to update after fault dispute upgrade

### ISSUE THREAD

**Issue by pegahcarter** [evmts/tevm-monorepo#1082]
It may be worth tackling the TODO for this object so that there is one less required dependency update after fault disputes are live on mainnet.  After the upgrade, these addresses should change:

https://github.com/evmts/tevm-monorepo/blob/71e5c1ead386f43a3bfbdd53acffcb5b49ad3433/extensions/opstack/scripts/generate.ts#L19-L20

**Comment by roninjin10** [comment]
@tevm/opstack is gone for now. Will come back later with support for interop fault proofs etc.
