### ISSUE TITLE
🐛Bug: `updatePragma` does not support multiple bounds for Solidity versions

### ISSUE THREAD

**Issue by emo-eth** [evmts/tevm-monorepo#1330]
The [updatePragma](https://github.com/evmts/tevm-monorepo/blob/main/bundler-packages/resolutions/src/utils/updatePragma.js#L20) util function fails on valid pragmas, namely those that specify upper and lower bounds, such as [Solarray](https://github.com/evmcheb/solarray/blob/master/src/Solarray.sol).

I believe `/pragma\s+solidity\s+((\^|~|>|>=|<|<=)?(\d+\.\d+\.\d+\s?)){1,2}\s*;/` should cover up to two bounds as well as extra whitespace before the semicolon (i.e., not run through a linter, but semantically correct Solidity).

**Comment by roninjin10** [comment]
Lol nice touch with the emoji. TIL you can specify both lower and upper bind

**Comment by roninjin10** [comment]
good call with the whitespace too

**Comment by roninjin10** [comment]
Fixed will release this plus remappings.txt support in a bit
