### ISSUE TITLE
Fix moduleResolution for ESM when using `nodenext`

### ISSUE THREAD

**Issue by sambacha** [evmts/tevm-monorepo#1384]
with "moduleResolution": "nodenext", if ESM resolves to index.d.ts, it'll have TS errors on the default import.  But if it resolves to index.d.mts the default import will work (even though both files have the same export default statement)

```bash
cp **/index.d.ts **/index.d.mts
```

then adjust exports in `package.json`

```jsonc
    ".": {
      "require": {
        "types": "./dist/index.d.ts",
        "default": "./dist/index.js"
      },
      "types": "./dist/index.d.mts",
      "default": "./dist/index.mjs"
    },
    "./*.mjs": {
      "types": "./dist/*.d.ts",
      "default": "./dist/*.mjs"
    },
    "./*.js": {
      "types": "./dist/*.d.ts",
      "default": "./dist/*.js"
    },
    "./*": {
      "types": "./dist/*.d.ts",
      "require": "./dist/*.js",
      "default": "./dist/*.mjs"
    }
  }
}
```

yes its that stupid

**Comment by roninjin10** [comment]
@sambacha can you give me a reproducible example. There are a lot more variables that go into this issue and will help me understand what is happening here

**Comment by roninjin10** [comment]
TypeScript should resolve this import in all cases. 
<img width="957" alt="image" src="https://github.com/user-attachments/assets/6a4a3c79-69b6-4cff-80b2-cf29eb359e8b">

Tevm has a `npm run lint:package` script that tests for compatability
<img width="751" alt="image" src="https://github.com/user-attachments/assets/f6eb3e7f-0943-48fd-9ad3-eff138bb2e7c">


Feel free to reopen with a reproducible example and I'm happy to look at it
