### ISSUE TITLE
bug: LSP regression in some editors in 0.10.0

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#476]
0.10.0 has a bug with the LSP not working. This seems to not affect vscode but does affect my vim lsp

**Comment by panukettu** [comment]
>This seems to not affect vscode 

seems broke for me if ts-plugin > 0.9.0 (vsc 1.84.0-insider)

`@evmts/ts-plugin >= 0.10.0` 

<img width="297" alt="SS 2023-10-08 at 3 02 28" src="https://github.com/evmts/evmts-monorepo/assets/18403470/bbcf9c9a-9e58-48f0-adb5-cb3c9fb35283">

`@evmts/ts-plugin == 0.9.0` 

<img width="411" alt="SS 2023-10-08 at 3 03 07" src="https://github.com/evmts/evmts-monorepo/assets/18403470/db229968-1e03-48fe-8a7e-e94b35fab55e">

**Comment by roninjin10** [comment]
@panukettu thanks for report! Can you link me to your code repro to debug please?

**Comment by roninjin10** [comment]
@panukettu also make sure you have workspace version of typescript enabled. Documentation for this is here: https://github.com/evmts/bun-starterkit#vscode-instructions

**Comment by panukettu** [comment]
repro by updating `@evmts/ts-plugin` in eg. next template: https://github.com/panukettu/evmts-tsplugin-repro

`WagmiReads.tsx:14`
<img width="577" alt="image" src="https://github.com/evmts/evmts-monorepo/assets/18403470/0b804ccb-1aa4-41d5-be08-8222419aeed5">

import itself has expected `EvmtsContract<...` type - TS just cannot tell about inner members. 

could be just problem with the type itself since `Go To Definition` jumps from .ts -> .sol as expected from methods eg. `contract.inner({ chainId }).SomeMethod`

**Comment by roninjin10** [comment]
Hmm interesting I wasn't able to repro 
<img width="804" alt="image" src="https://github.com/evmts/evmts-monorepo/assets/35039927/ae90d48a-fbc7-4ebf-8f58-2da2de029a9a">

**Comment by roninjin10** [comment]
Thinking if you see the abi correctly being passed into the type that seems like an issue with @evmts/core not the LSP itself. I'll try out on a different machine with no pnpm cache and your version of vscode and see if I can repro

**Comment by panukettu** [comment]
> Hmm interesting I wasn't able to repro <img alt="image" width="804" src="https://user-images.githubusercontent.com/35039927/273464970-ae90d48a-fbc7-4ebf-8f58-2da2de029a9a.png">

Right, if updating the npm package from old to new version then cmd shift p and "Restart TS server" in vscode is required (from tsconfig or ts file). If it works after that then nvm this issue.

For me any version bag of the packages won't work if I update the ts-plugin. 

Buuut anyways seems fine so far with the older version.

**Comment by roninjin10** [comment]
Awesome! Evmts 1.0 will be coming out in a few months and it will have a more robust way of importing contracts with better type hints.

**Comment by roninjin10** [comment]
Should be fixed if upgrading to latest evmts packages via `npm install @tevm/ts-plugin@next`. Tevm v1.0.0 is coming soon
