### ISSUE TITLE
Add predeploy option

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#763]
## Description

The [Tevm vm](https://github.com/evmts/tevm-monorepo/blob/main/vm/vm/src/tevm.ts#L105) currently takes a [minimal set of options](https://github.com/evmts/tevm-monorepo/blob/main/vm/vm/src/tevm.ts#L47). This ticket is to add the `predeploy` option.

## Spec 

A predeploy should be similar to how we do [precompiles](https://github.com/evmts/tevm-monorepo/pull/728/files#diff-9fc28d2f9eecc68f99b5636c97a297cfac22809cba05c0037003ddd6e99ac46fR6)

- a `definePredeploy` function that simply makes defining a predeploy typesafe similar to `definePrecompile` in the precompile pr
- a new createTevm optional paramater for taking additional predeploys
- precompiles should be placed into the state manager. See [putContractCode](https://github.com/evmts/tevm-monorepo/tree/main/vm/vm/src/actions/putContractCode)

```typescript
import {createTevm, definePredeploy} from '@tevm/vm'

const predeploy = definePredeploy({ 
  address: `0x${"0420".repeat(10)}`
  contract: createTevmContract({
    abi,
    deployedBytecode,
    name: "ExamplePredeploy",
  })
})

const tevm = createTevm({
  predeploys: [predeploy]
})

expect(
  await tevm.callContract({
    address: predeploy.address,
   ...predeploy.contract.read.exampleFunction()
).toBe('return value')
```0

## Tasks

- Add `definePredeploy` utility and export it from index.ts
- Add `predeploys` as a config option for `createTevm`
- Add unit tests
- Run `bun run all` within vm package rebuild documentation and make sure linter is up to date

**Comment by 0xNonCents** [comment]
Feel free to assign to me!

**Comment by roninjin10** [comment]
CHA-69
