### ISSUE TITLE
feat: create-evmts-app

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#82]
Fork scaffold eth?
Wagmi template?

**Comment by nissoh** [comment]
> Fork scaffold eth? Wagmi template?

vanilla TS with example of deployed artifacts? (;

**Comment by roninjin10** [comment]
@nissoh I'm thinking templates for many use cases
- vanilla ts
- vue
- wagmi-vite
- wagmi-next
- rspack
- rollup based library

As well as guides to add it to any project

**Comment by roninjin10** [comment]
For now because EVMts is still in alpha and might have many breaking changes we are going with forkable github repos to lower cost of maintaining this stuff and make it easier to upgrade when breaking changes do happened. This feature will be added after the beta release

**Comment by roninjin10** [comment]
Moving to linear
