### ISSUE TITLE
esbuild-plugin: addWatchFile not allowed outside supported hooks

### ISSUE THREAD

**Issue by chrisfarms** [evmts/tevm-monorepo#918]
esbuild doesn't like `addWatchFile` being called during `buildStart` 

```
[ERROR] unplugin/esbuild: addWatchFile outside supported hooks (resolveId, load, transform)
```

the offending line is the watch of the "tsconfig.json" file [here](https://github.com/evmts/tevm-monorepo/blob/main/bundler-packages/unplugin/src/tevmUnplugin.js#L74)

commenting out that line fixes things, just means needs a kick if tsconfig changes (which is very rare)  

version: `@tevm/esbuild-plugin@1.0.0-next.28`

**Comment by roninjin10** [comment]
Thank you this is fixed in this release https://github.com/evmts/tevm-monorepo/blob/89122f51e3755ab9c741783d2ed9b16bf4f0e7db/bundler-packages/unplugin/CHANGELOG.md?plain=1#L92
