### ISSUE TITLE
CallResult.gasUsed doesn't consider the specific cost of each byte in the tx data

### ISSUE THREAD

**Issue by 0xpolarzero** [evmts/tevm-monorepo#956]
## Description

The specific bytes read/written during a transaction use a different amount of gas, whether they are a zero (4 gas) or any non-zero (16 gas) value.

See these transactions ([1](https://sepolia.etherscan.io/tx/0x886c7e6d86a3a06d0d6c5cba40579551f0bb83c646f0247da9e326a4291183b2) and [2](https://sepolia.etherscan.io/tx/0x6a985f8e7556af5cc90c0c9ef4af90d0b031f090732ea4e9c5e77debe056cd39)), with a difference of exactly 50 bytes (zero => non-zero), which represent a difference of 600 gas (50 * (16-4)).

This difference in gas used in not caught in the Tevm environment, as both transactions would return the exact same amount of gas used. For reference, this is actually the same behavior as Forge (as of 2024-02-17).

See [this example with the same transactions as above](https://github.com/0xpolarzero/gas-metering-comparison/blob/main/tevm/index.ts). 

_This should not be mistaken with writing a state from zero to non-zero; it _does_ consider the overhead in such a case, e.g. sending an ERC20 token to an account with a `0` balance vs. with a `> 0` balance._

**Comment by roninjin10** [comment]
Thanks @0xpolarzero . This one isn't likely to be quick to track down so might be a bit before this issue is fixed

**Comment by roninjin10** [comment]
I believe this is handled when tevm mines tx. The `executionGasUsed` only takes into account the execution gas but some custom logic in `createTransaction.js` is where the tx data costs are calculated.

What I believe needs to happen here is `tevm_call` needs to return `executionGasUsed` and `gasUsed` where `gasUsed` is the actual gas used when the tx is mined

**Comment by roninjin10** [comment]
This is done using common a while back when we implemented vm.runTx. In fact if you change common you can change how pricing costs
