### ISSUE TITLE
Some contract calls will throw an unexpected TypeError in @tevm/actions/.../contractHandler

### ISSUE THREAD

**Issue by 0xpolarzero** [evmts/tevm-monorepo#958]
## Description

When simulating contract calls over an ERC20 contract, some calls will work as expected, but a specific `transfer` throws an error at the Tevm level. This will occur wether the call is supposed to succeed or not.

See [this code for reference](https://github.com/0xpolarzero/tevm-minimal-repro/blob/main/bug-contractHandler-join/index.ts).

## Version

tevm@1.0.0-next.39

### Console
```
node_modules/.pnpm/@tevm+actions@1.0.0-next.39_typescript@5.3.3/node_modules/@tevm/actions/src/tevm/contractHandler.js:37
                        ],
   ^
TypeError: Cannot read properties of undefined (reading 'join')
```

### contractHandler.js:37
```js
if (contract.length === 0 && !precompile) {
  return {
    rawData: '0x',
    executionGasUsed: 0n,
    errors: [
      {
        _tag: 'InvalidRequestError',
        name: 'InvalidRequestError',
        message: `Contract at address ${params.to} does not exist`,
      },
    ],
  };
}
```

**Comment by roninjin10** [comment]
Thanks for issue @0xpolarzero.  Contract call was getting reverted from insufficient funds but the error handling extracting the message had a bug in it.

Noticed something about your repro that I wanted to call out to help in future:

When you declare an abi you want to declare it `as const`. Declaring it `as const` will allow tevm to be typesafe for you.  For example, [this toString](https://github.com/0xpolarzero/tevm-minimal-repro/blob/main/bug-contractHandler-join/index.ts#L8) is wrong and it should be a bigint not a string. If you add an `as const` to your abis typescript will notice this.

**Comment by 0xpolarzero** [comment]
Thanks for the quick fix @roninjin10 and for the advice as well!

I had no idea I was making this mistake, although I did notice somehow that there was some kind of gap in the typesafety. That will definitely make things easier for me.
