### ISSUE TITLE
CallResult will sometimes return different gas used and refunded whether createTransaction is true or false

### ISSUE THREAD

**Issue by 0xpolarzero** [evmts/tevm-monorepo#960]
## Description

With some calls, depending on whether `Tevm.contract:createTransaction` is set to `true` or `false`, the returned `CallResult.executionGasUsed` and `CallResult.gasRefund` will be different.

Take [this example](https://github.com/0xpolarzero/tevm-minimal-repro/blob/main/bug-createTransaction-gas/index.ts) using two instances of the same token:

```js
// Mint some of each tokens and approve the airdrop contract for spending them
await mintAndApproveBoth(tevm);
// Airdrop tokens
const gasData = await airdropBoth(tevm);

...

// ? LOGS:
// ┌─────────┬─────────┬───────────┐
// │ (index) │ gasUsed │ gasRefund │
// ├─────────┼─────────┼───────────┤
// │  false  │  63218  │   29500   │
// │  true   │  51118  │   59700   │
// │  diff   │ -12100  │   30200   │
// └─────────┴─────────┴───────────┘
// ? 'airdropERC20' with createTransaction: true used 12,100 less gas
// ? and refunded 30,200 more gas than with createTransaction: false
```

In this example, while there is no difference in gas for regular `mint` and `approve` ERC20 interactions, calling `airdropERC20` on a custom airdrop contract will not return the same gas data whether the transaction is executed in a sandbox environment or in the same context as the previous ones.

Regardless of the parameters (lengths and values of the recipients/amounts), this will always return the same `12,100` decrease in gas used and `30,200` increase in gas refunded with `createTransaction: true`.

As a side note, compared to [a testnet transaction](https://sepolia.etherscan.io/tx/0x99e47380a615553df22c5863f6bad4fab11f7235ab4bd5c2b84f0a35892d1a43), the amount of gas used during execution seems more realistic with `createTransaction: false`.

## Version

tevm@1.0.0-next.39

**Comment by roninjin10** [comment]
The entire way gas is calculated has been updated
