### ISSUE TITLE
Feature request: return additional props on call result

### ISSUE THREAD

**Issue by 0xpolarzero** [evmts/tevm-monorepo#978]
### 1. `stateModified`

Return a `stateModified: boolean` prop on [`CallResult`](https://tevm.sh/reference/tevm/precompiles/type-aliases/callresult/), to indicate whether the contract/raw call did modify or not the state of the chain.

This would be even more useful as the ABI, depending on the provider, might not precisely return the state mutability of each function, or it might not be accurately written in the underlying contract.

### 2. `msg.value`

Return the value (in native tokens) sent along with a transaction. This would involve various other considerations that I'm not aware of; for instance, `skipBalance` being set to true, actually taking the gas fee from the caller at some point, etc?

**Comment by roninjin10** [comment]
Thought about this more and it will likely be a status

```typescript
type CallResult = {
 ...
  status: 'REVERTED' | 'CALL_SUCCESS' | 'TRANSACTION_SUCCESS' 
}
```

**Comment by roninjin10** [comment]
This is implicit now via tha `txHash` property.  If a tx actually updates the state it will return a txHash.

Note the state doesn't actually update until a new block is mined via calling `tevm.mine()` or automatically if automining is turned on.

I like the idea of adding `status` but for sake of keeping api surface small we will skip for now and strongly consider adding it later after more folks use tevm

> skipBalance being set to true, actually taking the gas fee from the caller at some point, etc?

Yea skipBalance will transfer eth to `from` address to cover both the `value` and not charge gas fees to the account when it later gets included in the chain. Note that we don't know the gas until the block is mined.

Detailed information can be gotten with `getTransactionReceipt` after block is mined
